import { useEffect,useRef,useState } from 'react'
import type { AppSettings,AvatarState,ChatRow,DocumentRow,ProviderConfig,RuntimeStatus } from '../../shared/contracts'

const view=new URLSearchParams(location.search).get('view')||'visitor'
export function App(){return view==='pet'?<Pet/>:view==='admin'?<AdminGate/>:<Visitor/>}
function useSettings(){const[s,setS]=useState<AppSettings>();useEffect(()=>{void window.desktop.settings.get().then(setS)},[]);return[s,setS]as const}
function useAssets(){const[a,setA]=useState<{logo:string;frames:Record<AvatarState,string[]>}>();const load=()=>window.desktop.assets.get().then(setA);useEffect(()=>{void load()},[]);return[a,load]as const}

function Visitor(){
 const[s]=useSettings(),[assets]=useAssets(),[history,setHistory]=useState<ChatRow[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[state,setState]=useState<AvatarState>('idle');const rec=useRef<MediaRecorder|undefined>(undefined);const chunks=useRef<Blob[]>([]),bottom=useRef<HTMLDivElement>(null)
 const refresh=async()=>setHistory(await window.desktop.chat.history());useEffect(()=>{void refresh();return window.desktop.events.onAvatarState(setState)},[]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[history]);useEffect(()=>{if(s)document.title=s.windowTitle},[s])
 async function ask(text=question){if(!text.trim()||busy)return;setQuestion('');setBusy(true);setHistory(x=>[...x,{id:Date.now(),role:'user',content:text,createdAt:new Date().toISOString()}]);try{const r=await window.desktop.chat.ask(text);await refresh();void playSpeech(r.answer)}catch(e){alert(msg(e));await refresh()}finally{setBusy(false)}}
 async function playSpeech(text:string){try{await playWav(await window.desktop.speech.speak(text))}catch(e){console.warn(e)}}
 async function record(){if(recording){rec.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);rec.current=r;r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=async()=>{setRecording(false);stream.getTracks().forEach(x=>x.stop());setBusy(true);try{const text=await window.desktop.speech.transcribe(await decode16k(new Blob(chunks.current)));setQuestion(text);if(text)await ask(text)}catch(e){alert(msg(e))}finally{setBusy(false)}};r.start();setRecording(true)}catch(e){alert(`无法使用麦克风：${msg(e)}`)}}
 if(!s)return <Loading/>;return <main className="visitor-shell"><header className="topbar glass"><div className="brand"><BrandMark logo={assets?.logo}/><div><h1>{s.visitorHeadline}</h1><p>{s.greetingText}</p></div></div><div className={`status ${state}`}><i/>{stateText(state)}</div><button className="icon-button" onClick={()=>window.desktop.app.openAdmin()}>⚙</button></header><section className="visitor-grid">
 <aside className="quick-panel glass"><span className="eyebrow">QUICK START</span><h2>大家都在问</h2><div className="quick-list">{s.quickQuestions.map((q,i)=><button key={`${i}-${q}`} onClick={()=>ask(q)}><b>{String(i+1).padStart(2,'0')}</b><span>{q}</span><em>↗</em></button>)}</div><div className="privacy-note">文档索引与语音识别支持本地运行</div></aside>
 <section className="chat-panel glass"><div className="chat-heading"><div><span className="eyebrow">CONVERSATION</span><h2>咨询对话</h2></div><button className="text-button" onClick={async()=>{await window.desktop.chat.clear();await refresh()}}>清空记录</button></div><div className="messages">{!history.length&&<div className="welcome"><Sprite state="idle" frames={assets?.frames}/><h3>很高兴见到你</h3><p>选择左侧问题，或在下方输入问题。</p></div>}{history.map(x=><article key={x.id} className={`message ${x.role}`}><span>{x.role==='user'?'你':'AI'}</span><div><p>{x.content}</p>{x.citations?.length?<details><summary>{x.citations.length} 条知识库依据</summary>{x.citations.map(c=><small key={c.id}>{c.sourceLabel} · {c.sourcePath}</small>)}</details>:null}</div></article>)}{busy&&<article className="message assistant"><span>AI</span><div className="typing"><i/><i/><i/></div></article>}<div ref={bottom}/></div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="输入问题，Enter 发送…"/><button className={`mic ${recording?'active':''}`} onClick={record}>{recording?'■':'◉'}<small>{recording?'结束':'语音'}</small></button><button className="send" disabled={busy||!question.trim()} onClick={()=>ask()}>发送 ↗</button></div></section>
 <aside className="assistant-card glass"><div className="orb"><div className="pet-preview"><Sprite state={state} frames={assets?.frames}/></div></div><span className="online"><i/> 本地服务已就绪</span><h2>{s.assistantName}</h2><p>知识库问答 · 本地语音 · 隐私友好</p><div className="capabilities"><div><b>ASR</b><span>语音识别</span></div><div><b>RAG</b><span>知识检索</span></div><div><b>VITS</b><span>语音播报</span></div></div><button className="secondary" onClick={()=>window.desktop.app.closeVisitor()}>暂时收起窗口</button></aside></section></main>
}

function AdminGate(){const[ok,setOk]=useState(false),[pin,setPin]=useState(''),[error,setError]=useState('');if(ok)return <Admin/>;return <main className="login-shell"><div className="login-card"><BrandMark/><span className="eyebrow">ADMIN ACCESS</span><h1>管理员验证</h1><p>请输入管理员密码进入控制中心</p><input type="password" autoFocus value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void verify()}} placeholder="默认密码 123456"/><button className="primary" onClick={verify}>进入管理员界面</button>{error&&<small>{error}</small>}</div></main>;async function verify(){if(await window.desktop.auth.verify(pin))setOk(true);else setError('密码错误')}}

function Admin(){
 const[s,setS]=useSettings(),[assets,reloadAssets]=useAssets(),[docs,setDocs]=useState<DocumentRow[]>([]),[runtime,setRuntime]=useState<RuntimeStatus>(),[tab,setTab]=useState<'knowledge'|'providers'|'content'|'security'>('knowledge'),[notice,setNotice]=useState(''),[selected,setSelected]=useState('dashscope'),[oldPin,setOldPin]=useState(''),[newPin,setNewPin]=useState('')
 const refresh=async()=>{setDocs(await window.desktop.knowledge.list());setRuntime(await window.desktop.app.runtimeStatus())};useEffect(()=>{void refresh()},[]);if(!s)return <Loading/>
 async function save(value:AppSettings){setS(await window.desktop.settings.save(value));setNotice('设置已保存');setTimeout(()=>setNotice(''),1800);await refresh();await reloadAssets()}
 return <main className="admin-shell"><aside className="admin-nav"><div className="admin-brand"><BrandMark logo={assets?.logo}/><div><b>控制中心</b><span>Knowledge Agent</span></div></div><nav><Nav active={tab==='knowledge'} onClick={()=>setTab('knowledge')} icon="▦" text="知识库"/><Nav active={tab==='providers'} onClick={()=>setTab('providers')} icon="◈" text="模型服务"/><Nav active={tab==='content'} onClick={()=>setTab('content')} icon="✦" text="界面与桌宠"/><Nav active={tab==='security'} onClick={()=>setTab('security')} icon="⌁" text="安全设置"/></nav><div className="admin-bottom"><button onClick={()=>window.desktop.app.showVisitor()}>↗ 打开访客端</button><small>Electron 2.1.0</small></div></aside><section className="admin-content"><header><div><span className="eyebrow">ADMIN CONSOLE</span><h1>{{knowledge:'知识库管理',providers:'模型与语音',content:'界面与桌宠',security:'安全设置'}[tab]}</h1></div>{notice&&<span className="saved">✓ {notice}</span>}<button className="primary" onClick={()=>save(s)}>保存更改</button></header>
 {tab==='knowledge'&&<><div className="stat-grid"><Stat label="已导入文档" value={`${docs.length}`} note="PDF / DOCX / TXT / MD / HTML"/><Stat label="知识片段" value={`${docs.reduce((n,d)=>n+d.chunks,0)}`} note="SQLite 本地持久化"/><Stat label="数据目录" value="本机" note={runtime?.dataDir||''}/></div><div className="admin-card"><div className="card-title"><div><h2>文档</h2><p>导入时自动解析、切分并建立索引。</p></div><button className="primary" onClick={async()=>{const r=await window.desktop.knowledge.import();setNotice(`导入 ${r.files} 个文档 / ${r.chunks} 个片段`);await refresh()}}>＋ 导入文档</button></div><div className="doc-table"><div className="table-head"><span>文档名称</span><span>片段</span><span>导入时间</span><span/></div>{docs.map(d=><div className="table-row" key={d.id}><span><b>{d.title}</b><small>{d.path}</small></span><span>{d.chunks}</span><span>{new Date(d.createdAt).toLocaleString()}</span><button onClick={async()=>{if(confirm(`删除 ${d.title}？`)){await window.desktop.knowledge.remove(d.id);await refresh()}}}>删除</button></div>)}</div></div></>}
 {tab==='providers'&&<ProviderSettings settings={s} setSettings={setS} selected={selected} setSelected={setSelected} runtime={runtime}/>}
 {tab==='content'&&<div className="form-grid"><div className="admin-card"><h2>标题与问候语</h2><Field label="窗口标题"><input value={s.windowTitle} onChange={e=>setS({...s,windowTitle:e.target.value})}/></Field><Field label="助手名称"><input value={s.assistantName} onChange={e=>setS({...s,assistantName:e.target.value})}/></Field><Field label="访客端标题"><input value={s.visitorHeadline} onChange={e=>setS({...s,visitorHeadline:e.target.value})}/></Field><Field label="问候语"><textarea value={s.greetingText} onChange={e=>setS({...s,greetingText:e.target.value})}/></Field><Field label="8 个预设问题（每行一条）"><textarea rows={10} value={s.quickQuestions.join('\n')} onChange={e=>setS({...s,quickQuestions:e.target.value.split('\n').slice(0,8)})}/></Field></div><div className="admin-card"><h2>用户资源</h2><div className="asset-preview"><BrandMark logo={assets?.logo}/><Sprite state="idle" frames={assets?.frames}/></div><Field label="Logo 路径（默认不提供）"><input readOnly value={s.assets.logoPath}/><button className="secondary" onClick={async()=>{const p=await window.desktop.assets.chooseLogo();if(p)setS({...s,assets:{...s.assets,logoPath:p}})}}>选择</button></Field><Field label="桌宠序列帧根目录"><input readOnly value={s.assets.petFramesPath}/><button className="secondary" onClick={async()=>{const p=await window.desktop.assets.choosePetFrames();if(p)setS({...s,assets:{...s.assets,petFramesPath:p}})}}>选择</button></Field><p className="muted">仓库不附带 Logo；用户可自行选择图片。桌宠目录可包含 idle、listening、thinking、speaking、error 五个子目录。</p><Field label="桌宠台词（每行一条）"><textarea rows={7} value={s.pet.dialogues.join('\n')} onChange={e=>setS({...s,pet:{...s.pet,dialogues:e.target.value.split('\n').filter(Boolean)}})}/></Field><Field label="动画帧间隔 ms"><input type="number" min="60" max="1000" value={s.pet.frameIntervalMs} onChange={e=>setS({...s,pet:{...s.pet,frameIntervalMs:Number(e.target.value)}})}/></Field></div></div>}
 {tab==='security'&&<div className="form-grid"><div className="admin-card"><h2>修改管理员密码</h2><p className="muted">默认密码为 123456，新密码至少 6 位。</p><Field label="当前密码"><input type="password" value={oldPin} onChange={e=>setOldPin(e.target.value)}/></Field><Field label="新密码"><input type="password" value={newPin} onChange={e=>setNewPin(e.target.value)}/></Field><button className="primary security-save" onClick={async()=>{const ok=await window.desktop.auth.change(oldPin,newPin);setNotice(ok?'密码已修改':'当前密码错误或新密码不足 6 位');if(ok){setOldPin('');setNewPin('')}}}>修改密码</button></div></div>}
 </section></main>
}

function ProviderSettings({settings,setSettings,selected,setSelected,runtime}:{settings:AppSettings;setSettings(value:AppSettings):void;selected:string;setSelected(value:string):void;runtime?:RuntimeStatus}){
 const[query,setQuery]=useState(''),[fetching,setFetching]=useState<string>(),[modelNotice,setModelNotice]=useState('')
 const provider=settings.providers.find(x=>x.id===selected)||settings.providers[0]
 const active=settings.providers.filter(x=>x.enabled)
 const updateProvider=(id:string,patch:Partial<ProviderConfig>)=>setSettings({...settings,providers:settings.providers.map(x=>x.id===id?{...x,...patch}:x)})
 const chooseCapabilityProvider=(kind:'embedding'|'asr',id:string)=>{const p=settings.providers.find(x=>x.id===id);if(!p)return;setSettings({...settings,activeProviders:{...settings.activeProviders,[kind]:id},[kind]:{...settings[kind],providerId:id,model:kind==='embedding'?p.embeddingModel:p.asrModel}})}
 const chooseCapabilityModel=(kind:'embedding'|'asr',id:string,model:string)=>{const key=kind==='embedding'?'embeddingModel':'asrModel';setSettings({...settings,[kind]:{...settings[kind],model},providers:settings.providers.map(x=>x.id===id?{...x,[key]:model}:x)})}
 const fetchModels=async(id:string)=>{const target=settings.providers.find(x=>x.id===id);if(!target)return;setFetching(id);setModelNotice(`正在从 ${target.name} 获取模型…`);try{const modelCatalog=await window.desktop.providers.listModels(target);const next={...target,modelCatalog,chatModel:modelCatalog.chat.includes(target.chatModel)?target.chatModel:modelCatalog.chat[0]||'',embeddingModel:modelCatalog.embedding.includes(target.embeddingModel)?target.embeddingModel:modelCatalog.embedding[0]||'',asrModel:modelCatalog.asr.includes(target.asrModel)?target.asrModel:modelCatalog.asr[0]||''};setSettings({...settings,providers:settings.providers.map(x=>x.id===id?next:x),embedding:settings.embedding.providerId===id?{...settings.embedding,model:next.embeddingModel}:settings.embedding,asr:settings.asr.providerId===id?{...settings.asr,model:next.asrModel}:settings.asr});setModelNotice(`已获取 ${modelCatalog.all.length} 个模型：对话 ${modelCatalog.chat.length}、Embedding ${modelCatalog.embedding.length}、ASR ${modelCatalog.asr.length}`)}catch(e){setModelNotice(msg(e))}finally{setFetching(undefined)}}
 const embeddingProvider=settings.providers.find(x=>x.id===settings.embedding.providerId)
 const asrProvider=settings.providers.find(x=>x.id===settings.asr.providerId)
 return <div className="provider-layout"><div className="provider-list admin-card"><h2>服务商（{settings.providers.length}）</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索服务商"/><div>{settings.providers.filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(query.toLowerCase())).map(p=><button className={p.id===provider.id?'active':''} onClick={()=>setSelected(p.id)} key={p.id}><i className={p.enabled?'on':''}/><span>{p.name}</span></button>)}</div></div><div className="provider-settings-stack">
  <div className="admin-card provider-form"><div className="card-title"><div><h2>{provider.name}</h2><p>{provider.id} · 已缓存 {provider.modelCatalog.all.length} 个模型</p></div><label className="switch"><input type="checkbox" checked={provider.enabled} onChange={e=>updateProvider(provider.id,{enabled:e.target.checked})}/><span>启用</span></label></div><div className="two-col"><Field label="接口协议"><select value={provider.protocol} onChange={e=>updateProvider(provider.id,{protocol:e.target.value as ProviderConfig['protocol']})}><option value="openai">OpenAI-compatible</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option><option value="azure-openai">Azure OpenAI</option><option value="custom">自定义</option></select></Field><Field label="Base URL"><input value={provider.baseUrl} onChange={e=>updateProvider(provider.id,{baseUrl:e.target.value})}/></Field></div><Field label="API Key"><input type="password" value={provider.apiKey} onChange={e=>updateProvider(provider.id,{apiKey:e.target.value})}/></Field><div className="model-fetch-row"><button className="primary" disabled={fetching===provider.id} onClick={()=>fetchModels(provider.id)}>{fetching===provider.id?'获取中…':'实时获取模型'}</button><span>{modelNotice||'调用服务商模型列表接口；下架模型会从下拉列表移除。'}</span></div><div className="three-col"><ModelField label="对话模型" value={provider.chatModel} models={provider.modelCatalog.chat} onChange={model=>updateProvider(provider.id,{chatModel:model})}/><ModelField label="Embedding 模型" value={provider.embeddingModel} models={provider.modelCatalog.embedding} onChange={model=>updateProvider(provider.id,{embeddingModel:model})}/><ModelField label="ASR 模型" value={provider.asrModel} models={provider.modelCatalog.asr} onChange={model=>updateProvider(provider.id,{asrModel:model})}/></div></div>
  <div className="admin-card capability-card"><div className="card-title"><div><h2>对话模型</h2><p>服务商 → 该服务商提供的对话模型</p></div></div><div className="two-col"><Field label="服务商"><select value={settings.activeProviders.chat} onChange={e=>setSettings({...settings,activeProviders:{...settings.activeProviders,chat:e.target.value}})}>{active.map(option)}</select></Field>{(()=>{const p=settings.providers.find(x=>x.id===settings.activeProviders.chat);return p?<ModelField label="模型" value={p.chatModel} models={p.modelCatalog.chat} onChange={model=>updateProvider(p.id,{chatModel:model})}/>:null})()}</div></div>
  <div className="admin-card capability-card"><div className="card-title"><div><h2>Embedding</h2><p>本地优先，远程模式按服务商实时选择模型</p></div></div><div className="three-col"><Field label="运行方式"><select value={settings.embedding.mode} onChange={e=>{const mode=e.target.value as AppSettings['embedding']['mode'],remote=embeddingProvider||active[0];setSettings({...settings,activeProviders:{...settings.activeProviders,embedding:mode==='remote'?(remote?.id||''):settings.activeProviders.embedding},embedding:{...settings.embedding,mode,providerId:mode==='remote'?(remote?.id||'local'):'local',model:mode==='remote'?(remote?.embeddingModel||''):mode==='hash'?'hash-384':'Xenova/bge-small-zh-v1.5'}})}}><option value="local-onnx">本地 BGE ONNX</option><option value="hash">本地 Hash 应急</option><option value="remote">云端服务商</option></select></Field>{settings.embedding.mode==='remote'?<><Field label="服务商"><select value={settings.embedding.providerId} onChange={e=>chooseCapabilityProvider('embedding',e.target.value)}>{active.map(option)}</select></Field><ModelField label="服务商模型" value={settings.embedding.model} models={embeddingProvider?.modelCatalog.embedding||[]} onChange={model=>chooseCapabilityModel('embedding',settings.embedding.providerId,model)}/></>:<ModelField label="本地模型" value={settings.embedding.model} models={settings.embedding.mode==='hash'?['hash-384']:['Xenova/bge-small-zh-v1.5','Xenova/bge-base-zh-v1.5']} onChange={model=>setSettings({...settings,embedding:{...settings.embedding,model}})}/>}</div>{settings.embedding.mode==='remote'&&embeddingProvider&&<button className="secondary compact" onClick={()=>fetchModels(embeddingProvider.id)}>刷新该服务商模型</button>}<Runtime label="Embedding" text={runtime?.embedding}/></div>
  <div className="admin-card capability-card"><div className="card-title"><div><h2>ASR 语音识别</h2><p>本地 Whisper 或云端服务商 → ASR 模型</p></div></div><div className="three-col"><Field label="运行方式"><select value={settings.asr.mode} onChange={e=>{const mode=e.target.value as AppSettings['asr']['mode'],remote=asrProvider||active[0];setSettings({...settings,activeProviders:{...settings.activeProviders,asr:mode==='remote'?(remote?.id||''):settings.activeProviders.asr},asr:{...settings.asr,mode,providerId:mode==='remote'?(remote?.id||'local'):'local',model:mode==='remote'?(remote?.asrModel||''):'onnx-community/whisper-small'}})}}><option value="local-onnx">本地 Whisper ONNX</option><option value="remote">云端服务商</option></select></Field>{settings.asr.mode==='remote'?<><Field label="服务商"><select value={settings.asr.providerId} onChange={e=>chooseCapabilityProvider('asr',e.target.value)}>{active.map(option)}</select></Field><ModelField label="服务商 ASR 模型" value={settings.asr.model} models={asrProvider?.modelCatalog.asr||[]} onChange={model=>chooseCapabilityModel('asr',settings.asr.providerId,model)}/></>:<><ModelField label="本地模型" value={settings.asr.model} models={['onnx-community/whisper-tiny','onnx-community/whisper-small','onnx-community/whisper-medium']} onChange={model=>setSettings({...settings,asr:{...settings.asr,model}})}/><Field label="识别语言"><select value={settings.asr.language} onChange={e=>setSettings({...settings,asr:{...settings.asr,language:e.target.value}})}><option value="zh">中文</option><option value="en">English</option><option value="auto">自动检测</option></select></Field></>}</div>{settings.asr.mode==='remote'&&asrProvider&&<button className="secondary compact" onClick={()=>fetchModels(asrProvider.id)}>刷新该服务商模型</button>}<Runtime label="ASR" text={runtime?.asr}/></div>
  <div className="admin-card capability-card"><div className="card-title"><div><h2>TTS 本地语音</h2><p>保留一个内置 VITS 方案，可覆盖运行文件路径</p></div></div><div className="two-col"><Field label="TTS 程序路径"><input value={settings.tts.executablePath} placeholder="留空使用便携版内置" onChange={e=>setSettings({...settings,tts:{...settings.tts,executablePath:e.target.value}})}/></Field><Field label="TTS 模型路径"><input value={settings.tts.modelPath} placeholder="留空使用便携版内置" onChange={e=>setSettings({...settings,tts:{...settings.tts,modelPath:e.target.value}})}/></Field></div><Runtime label="TTS" text={runtime?.tts}/><button className="secondary" onClick={async()=>{try{await playWav(await window.desktop.speech.speak('您好，本地语音服务测试正常。'))}catch(e){alert(msg(e))}}}>测试 TTS</button></div>
 </div></div>
}

function ModelField({label,value,models,onChange}:{label:string;value:string;models:string[];onChange(value:string):void}){const options=value&&!models.includes(value)?[value,...models]:models;return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}><option value="">{models.length?'请选择模型':'请先获取模型'}</option>{options.map(model=><option key={model} value={model}>{model}</option>)}</select></Field>}
function BrandMark({logo}:{logo?:string}){return logo?<img className="user-logo" src={logo}/>:<span className="brand-placeholder" aria-label="未配置 Logo">AI</span>}

function Pet(){const[s]=useSettings(),[assets]=useAssets(),[state,setState]=useState<AvatarState>('idle'),[line,setLine]=useState(0);const moved=useRef(false),start=useRef({x:0,y:0}),raf=useRef(0);useEffect(()=>window.desktop.events.onAvatarState(setState),[]);useEffect(()=>{const t=setInterval(()=>setLine(x=>(x+1)%Math.max(1,s?.pet.dialogues.length||1)),5000);return()=>clearInterval(t)},[s?.pet.dialogues.length]);return <div className="desktop-pet" onPointerDown={e=>{moved.current=false;start.current={x:e.screenX,y:e.screenY};void window.desktop.pet.beginDrag();e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!e.buttons)return;if(Math.hypot(e.screenX-start.current.x,e.screenY-start.current.y)>3)moved.current=true;if(!raf.current)raf.current=requestAnimationFrame(()=>{raf.current=0;void window.desktop.pet.drag()})}} onPointerUp={()=>{void window.desktop.pet.endDrag();if(!moved.current)void window.desktop.app.showVisitor()}} onContextMenu={e=>{e.preventDefault();void window.desktop.pet.showMenu()}}><div className="pet-bubble">{state==='idle'?(s?.pet.dialogues[line]||'点我咨询'):stateText(state)}</div><Sprite state={state} frames={assets?.frames} interval={s?.pet.frameIntervalMs}/><div className="pet-shadow"/></div>}
function Sprite({state,frames,interval=140}:{state:AvatarState;frames?:Record<AvatarState,string[]>;interval?:number}){const[f,setF]=useState(0),list=frames?.[state]||[];useEffect(()=>{setF(0);const t=setInterval(()=>setF(x=>(x+1)%Math.max(1,list.length)),Math.max(60,interval));return()=>clearInterval(t)},[state,list.length,interval]);if(!list.length)return <div className={`sprite-placeholder ${state}`}>AI</div>;return <img draggable={false} src={list[f%list.length]}/>}
function Nav(p:{active:boolean;onClick():void;icon:string;text:string}){return <button className={p.active?'active':''} onClick={p.onClick}>{p.icon}<span>{p.text}</span></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span><div>{children}</div></label>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <div className="stat admin-card"><span>{label}</span><b>{value}</b><small>{note}</small></div>}
function Runtime({label,text}:{label:string;text?:string}){return <div className="runtime-row"><i/><div><b>{label}</b><span>{text||'读取中…'}</span></div></div>}
function Loading(){return <div className="loading"><i/><span>正在初始化本地服务…</span></div>}
function enabled(p:ProviderConfig[]){return p.filter(x=>x.enabled)}function option(p:ProviderConfig){return <option key={p.id} value={p.id}>{p.name}</option>}
function stateText(s:AvatarState){return{idle:'待命',listening:'聆听中',thinking:'思考中',speaking:'播报中',error:'需要检查'}[s]}function msg(e:unknown){return e instanceof Error?e.message:String(e)}
async function playWav(bytes:Uint8Array){if(!bytes?.byteLength)throw new Error('TTS 没有返回音频数据');const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);const url=URL.createObjectURL(new Blob([copy.buffer],{type:'audio/wav'}));try{const audio=new Audio(url);await new Promise<void>((resolve,reject)=>{audio.onended=()=>resolve();audio.onerror=()=>reject(new Error('音频解码或播放失败'));void audio.play().catch(reject)})}finally{URL.revokeObjectURL(url)}}
async function decode16k(blob:Blob){const c=new AudioContext(),d=await c.decodeAudioData(await blob.arrayBuffer()),o=new OfflineAudioContext(1,Math.ceil(d.duration*16000),16000),src=o.createBufferSource();src.buffer=d;src.connect(o.destination);src.start();const r=await o.startRendering();await c.close();return r.getChannelData(0).slice()}
