import type { ProviderConfig, ProviderProtocol } from './contracts'

type Entry = [string, string, string, ProviderProtocol?]
const entries: Entry[] = [
  ['openai','OpenAI','https://api.openai.com/v1'],['anthropic','Anthropic','https://api.anthropic.com/v1','anthropic'],['gemini','Google Gemini','https://generativelanguage.googleapis.com/v1beta','gemini'],['azure-openai','Azure OpenAI','', 'azure-openai'],
  ['dashscope','阿里云百炼 / 通义','https://dashscope.aliyuncs.com/compatible-mode/v1'],['deepseek','DeepSeek','https://api.deepseek.com'],['silicon','硅基流动','https://api.siliconflow.cn/v1'],['zhipu','智谱 BigModel','https://open.bigmodel.cn/api/paas/v4'],['moonshot','Moonshot / Kimi','https://api.moonshot.cn/v1'],['minimax','MiniMax 中国','https://api.minimaxi.com/v1'],['minimax-global','MiniMax Global','https://api.minimax.io/v1'],
  ['openrouter','OpenRouter','https://openrouter.ai/api/v1'],['ollama','Ollama','http://localhost:11434/v1'],['lmstudio','LM Studio','http://localhost:1234/v1'],['new-api','New API / One API','http://localhost:3000/v1'],['gpustack','GPUStack','http://localhost:80/v1'],['localai','LocalAI','http://localhost:8080/v1'],['xinference','Xinference','http://localhost:9997/v1'],['openllm','OpenLLM','http://localhost:3000/v1'],
  ['groq','Groq','https://api.groq.com/openai/v1'],['mistral','Mistral','https://api.mistral.ai/v1'],['together','Together AI','https://api.together.xyz/v1'],['fireworks','Fireworks AI','https://api.fireworks.ai/inference/v1'],['perplexity','Perplexity','https://api.perplexity.ai'],['xai','xAI / Grok','https://api.x.ai/v1'],['cerebras','Cerebras','https://api.cerebras.ai/v1'],['sambanova','SambaNova','https://api.sambanova.ai/v1'],
  ['github','GitHub Models','https://models.github.ai/inference'],['huggingface','Hugging Face','https://router.huggingface.co/v1'],['modelscope','ModelScope','https://api-inference.modelscope.cn/v1'],['nvidia','NVIDIA NIM','https://integrate.api.nvidia.com/v1'],['novita','Novita AI','https://api.novita.ai/v3/openai'],['hyperbolic','Hyperbolic','https://api.hyperbolic.xyz/v1'],
  ['doubao','火山方舟 / 豆包','https://ark.cn-beijing.volces.com/api/v3'],['hunyuan','腾讯混元','https://api.hunyuan.cloud.tencent.com/v1'],['tencent-cloud-ti','腾讯云 TI','https://api.lkeap.cloud.tencent.com/v1'],['baidu-cloud','百度千帆','https://qianfan.baidubce.com/v2'],['baichuan','百川智能','https://api.baichuan-ai.com/v1'],['stepfun','阶跃星辰','https://api.stepfun.com/v1'],['yi','零一万物','https://api.lingyiwanwu.com/v1'],['longcat','美团 LongCat','https://api.longcat.chat/openai'],['mimo','小米 MiMo','https://api.xiaomimimo.com/v1'],
  ['cohere','Cohere','https://api.cohere.com/compatibility/v1'],['jina','Jina AI','https://api.jina.ai/v1'],['voyage','Voyage AI','https://api.voyageai.com/v1'],['upstage','Upstage','https://api.upstage.ai/v1/solar'],['nomic','Nomic','https://api-atlas.nomic.ai/v1'],['mixedbread','Mixedbread','https://api.mixedbread.ai/v1'],
  ['aihubmix','AiHubMix','https://aihubmix.com/v1'],['302ai','302.AI','https://api.302.ai/v1'],['ppio','PPIO','https://api.ppinfra.com/v3/openai'],['qiniu','七牛云','https://api.qnaigc.com/v1'],['gitee-ai','Gitee AI','https://ai.gitee.com/v1'],['infini','无问芯穹','https://cloud.infini-ai.com/maas/v1'],['zai','Z.AI','https://api.z.ai/api/paas/v4'],
  ['openai-compatible','OpenAI API Compatible',''],['custom','自定义服务商','', 'custom'],['bedrock','AWS Bedrock','', 'custom'],['vertex-ai','Google Vertex AI','', 'gemini'],['azure-ai-studio','Azure AI Studio','', 'custom'],['sagemaker','AWS SageMaker','', 'custom'],['oci','Oracle OCI','', 'custom'],['replicate','Replicate','https://api.replicate.com/v1','custom'],['poe','Poe','https://api.poe.com/v1'],['vessl-ai','VESSL AI',''],['leptonai','Lepton AI',''],['regolo','Regolo',''],['perfxcloud','PerfXCloud',''],['deerapi','DeerAPI',''],['cometapi','CometAPI','']
]

export const providerCatalog: ProviderConfig[] = entries.map(([id,name,baseUrl,protocol='openai']) => ({
  id,name,baseUrl,protocol,apiKey:'',chatModel:'',embeddingModel:'',asrModel:'',enabled:false,
  modelCatalog:{all:[],chat:[],embedding:[],asr:[]}
}))
